### ISSUE TITLE
Request for a major version release and restore v4 without breaking changes

### ISSUE THREAD

**Issue by CharlieGarcia** [mplatt/fold-to-ascii#10]
## Fold is not a function
Last changes introduced in this library, specifically the ones introduced in this commit in particular: https://github.com/mplatt/fold-to-ascii/commit/4cf57c75f61396e421255ac26c2e69dcb6472497#diff-e9ef0426c130f92ae3cda5a4b3d0356fL32. Must be considered as a breaking change and probably should be managed as a major release of the package. `v5.0.0` 

If I do this:
```
{ fold } = require('fold-to-ascii'),
```

I end up with an error that says `fold` is not a function.

**Comment by diachedelic** [comment]
this broke my production API!

**Comment by retorquere** [comment]
For the 4 line, fold could just be added back as an alias for foldMaintaining, with perhaps a depreciation warning.

**Comment by mplatt** [comment]
Re-introduced `fold(str, replacement)` in _4.1.2_ to appease semver wildcard users and removed it in a subsequent _5.0.0_ release.
