### ISSUE TITLE
Broken in Typescript 4.4

### ISSUE THREAD

**Issue by nghiepit** [mplatt/fold-to-ascii#12]
Hi,
`fold-to-ascii` has been broken in the new version of Typescript 4.4.
>Cannot read property '_fold' of undefined

```ts
import { foldReplacing } from "fold-to-ascii";
foldReplacing("test string");
```

Reproduction: https://codesandbox.io/s/fold-to-ascii-typescript-4-4-broken-xxkc4

**Comment by Seblor** [comment]
Since `this` is unbound if you only import the static method, you will need to import the class to access it like so:

    import ASCIIFolder from "fold-to-ascii";
    console.log(ASCIIFolder.foldReplacing("test string"));

**Comment by nghiepit** [comment]
thanks @Seblor import the class it works.
I don't know should I close this issue or not.

**Comment by Seblor** [comment]
I think that would be up to @mplatt since it seems to be a normal behavior from JS / TS, but the binding can be enforced by either changing the way to export the function (not using a class), or with those lines before exporting: 

```js
ASCIIFolder._fold = ASCIIFolder._fold.bind(ASCIIFolder)
ASCIIFolder.foldMaintaining = ASCIIFolder.foldMaintaining.bind(ASCIIFolder)
ASCIIFolder.foldReplacing = ASCIIFolder.foldReplacing.bind(ASCIIFolder)```

**Comment by ruudvanbuul** [comment]
Problem is that all methods are static and you can never use this. in a static method cause there is no instance of the class.

Fix:
`ASCIIFolder._fold()`

instead of:
`this._fold()`
