### ISSUE TITLE
ES5 version?

### ISSUE THREAD

**Issue by retorquere** [mplatt/fold-to-ascii#5]
Would it be possible to offer an ES5 version alongside the ES6 version by running it through something like Babel?

**Comment by youknowriad** [comment]
May be this would do the trick https://github.com/mplatt/fold-to-ascii/pull/6

**Comment by mplatt** [comment]
Happy to look into that. In the meantime you can always use 2.0.2. It's the same API

**Comment by youknowriad** [comment]
@mplatt ah ok, I was not aware of that. thanks

**Comment by mplatt** [comment]
updated readme to reflect this
