### ISSUE TITLE
Doesn't handle eggplant

### ISSUE THREAD

**Issue by dteoh** [mplatt/fold-to-ascii#8]
I tried the following in Chrome and Firefox.

```
> ASCIIFolder.fold("🍆", null)
"null"
> ASCIIFolder.fold("こんにちは", null)
"nullnullnullnullnull"
> ASCIIFolder.fold("お早うございます", null)
"nullnullnullnullnullnullnullnull"
```

According to the docs, all cases should not have performed any character replacements.

**Comment by mplatt** [comment]
It should work as you expect:

 - https://github.com/mplatt/fold-to-ascii/blob/master/test/ascii-folder.js#L38
 - https://github.com/mplatt/fold-to-ascii/blob/master/test/ascii-folder.js#L46

If you're using the package from npm, try using the version from master instead. If it still doesn't work, maybe it's related to your browser. It would be great to get the QUnit output from your browser in that case.

**Comment by dteoh** [comment]
Thanks, upgrading from 4.0.0 to 4.1.1 seems to have fixed the issue.
